import Link from "next/link";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/dist/client/router";




function Manager() {
  const { data: session } = useSession();
  const router = useRouter();

  console.log("session", session);



  return <div className="main">
  <Head>
        <title>Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
  <h1 className="text-4xl font-bold">Manager Administration</h1>
  <p>&nbsp;</p>
  {session ? (
          <button onClick={() => signOut()}>Log out</button>
        ) : (
          <button
            onClick={() => {
              router.push("/api/auth/signin");
            }}
          >
            Sign in
          </button>
        )}
  

  <p>&nbsp;</p>
  <p>&nbsp;</p>
  
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <div className="page-nav">
    <Link href="/shelterapi/adoptAppCreate">New Adoption Application</Link>
  </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/shelterapi">All Shelter Animals</Link>
        </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/shelterapi/dogs">Dogs</Link>
        </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/shelterapi/cats">Cats</Link>
        </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/shelterapi/thecats">The Cats</Link>
        </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/shelterapi/thedogs">The Dogs</Link>
        </div>
  <p>&nbsp;</p>

   <div>
    <ul>
    {session && session.isAdmin && (
  <li className="-mb-px mr-1">    
    <Link className="bg-white inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/shelterapi">All Animals</Link>
  </li>
  )}
  {session && session.isAdmin && (
  <li className="mr-1">
  <Link className="bg-white inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/notes">Notes</Link>
  </li>
)}
{session && session.isAdmin && (
  <li className="mr-1">
  <Link className="bg-white inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/photos">Photos</Link>
  </li>
)}
{session && session.isAdmin && (
  <li className="mr-1">
  <Link className="bg-white inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/shelterapi">Shelter API</Link>
  </li>
)}
  
  {session && session.isAdmin && (
  <li className="mr-1">
  <Link className="bg-white inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/users">Users</Link>
  </li>
)}
    </ul>
   </div>         




  </div>

   


}

export default Manager