import Link from "next/link";
import Head from "next/head";
import { signOut, useSession, signIn } from "next-auth/react";




export default function ShelterApi({ data }) {
  const { data: session } = useSession();
  //const { data: session } = useSession();
  let myid;
  
  if (session) 
    myid = session.id; 
  else
    myid = 0;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>API Adoption Applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

            
      {session && session.isAdmin && (
      <main className="main">
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="">Add New App</Link>
        </div>
        <p>&nbsp;</p>
        <h1 className="text-2xl font-black">All Applications</h1>
        <p>&nbsp;</p>
            
        <ul>
          {data.map((item) => (
            <li key={item.id}>
              <b>Full Name: {item.name}</b>
              <br />
              <p>Animal Name: {item.nameAnimal}</p>
              <p>Email: {item.email}</p>
              <p>ID: {item.id}</p>
              <p>Adopter ID: {item.adopter_id}</p>
              
              <div className="page-nav">
                <Link href={`/shelterapi/detailAdoptApp/${item.id}`}>
                  Details
                </Link>
                <p>&nbsp;</p>
              </div>
                          
            </li>
            
          ))}
        </ul>
        
      </main>
      )}

      <footer className="text-center font-bold text-xl">
        <b>SPCAPV 2023</b>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  //const notes = await prisma.note.findMany();
  //const res = await fetch(`https://shelter.spcapv.net/adopt/adopt_app_list`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/adopt_app_list`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/dogs`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/cats`)
  const data = await res.json()
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props: { data: data },
  };
}