import Link from "next/link";
import Head from "next/head";




export default function ShelterApi({ data }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>API Adoption Applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="">Add New App</Link>
        </div>
        <p>&nbsp;</p>
        <h1 className="text-2xl font-black">All Applications</h1>
        <p>&nbsp;</p>

        <ul>
          {data.map((item) => (
            <li key={item.id}>
              <b>Full Name: {item.name}</b>
              <br />
              <p>Animal Name: {item.nameAnimal}</p>
              <p>Email: {item.email}</p>
              <p>ID: {item.id}</p>
              
              <div className="page-nav">
                <Link href={`/shelterapi/detailAdoptApp/${item.id}`}>
                  Details
                </Link>
              </div>
              &nbsp;
            </li>
          ))}
        </ul>
      </main>

      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  //const notes = await prisma.note.findMany();
  //const res = await fetch(`https://shelter.spcapv.net/adopt/adopt_app_list`)
  const res = await fetch(`http://127.0.0.1:8000/adopt/adopt_app_list`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/dogs`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/cats`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props: { data },
  };
}
