import Link from "next/link";
import Head from "next/head";
import Image from 'next/image'
//import prisma from "../../lib/prisma.ts";




export default function ShelterApi({ data }) {
  return (

    <div>
      <Head>
        <title>Cats - Available</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-10 flex-wrap">
        <div className="w-96 p-5">
      
          
      <h1 className="text-2xl font-black">Cats Available For Adoption</h1>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <ul>
          {data.map((item) => (
            <li key={item.id}>
         <div className="p-5">   
        <div className="card card-side w-96 bg-base-100 shadow-2xl">
  <figure><img src={item.photoMedium} alt={item.name} /></figure>
  <div className="card-body">
    <h2 className="card-title">
    {item.name}
      <div className="badge badge-warning">Available!</div>
    </h2>  
    <p className="text-sm">Gender: {item.gender}<br />
    Weight: {item.weight}<br />
    Age:&nbsp; 
    {item.myage == 0 && (
      <span>&lt; 1 Year</span>
     )}
     {item.myage > 0 && (
      <span>{item.myage}</span>
     )}

     
      </p>
              
    <div className="card-actions justify-end">
    <Link className="badge badge-outline" href={`/shelterapi/animal_details/${item.id}`}>Details</Link>  
    
      
    </div>
  </div>
</div>        
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>

</li>

          ))}
        </ul>







      </div>

      <div className="flex-auto ml-10 w-64 h-14 p-10">
          <h1 className="text-2xl font-black">HOW THIS WORKS:</h1>
            <p>
            Once you have determined the specific animal you wish 
            to adopt, you are ready to start on your Adoption Application.
            </p>
            <p>&nbsp;</p>

            
            <h1 className="text-1xl font-black">Mexico and USA Residents:</h1>
            <p>&nbsp;</p>
            <ul className="list-disc">
            <li>
            If you want to adopt one of our dogs or cats, and you 
            are a resident of Mexico or the United States, use the 
            Adoption Application on this website.
            </li>
            </ul>
            
            <p>&nbsp;</p>
            <h1 className="text-1xl font-black">Canada Residents:</h1>
            <p>&nbsp;</p>
            <ul className="list-disc">
            <li>
            If you are a resident of Canada and you want to adopt 
            one of our dogs, please use the PVCA Adoption 
            Application here.  You can download the form, 
            fill it out and email it to us at spcapv@gmail.com.
            <br />&nbsp;
            </li>
            <li>
            <Link href="https://spcapvr.com/wp-content/uploads/2022/08/ADOPTION-APPLICATION.pdf">
            <u><b>Canada PVCA Addoption Application - Dogs - Download</b></u>
            </Link>
            <br />&nbsp;
            </li>
              <li>        
            If you are in Canada and want to adopt one of 
            our cats, use this website and the online Adoption 
            Application.  
            </li>
            </ul>
            <p>&nbsp;</p>

            <h1 className="text-1xl font-black">Adoption Fees</h1>
            <p>&nbsp;</p>
            <ul className="list-disc">
            <li>Adoption Fees for Dogs:<br />
            Mexico: $3,000 pesos<br />
            US and Canada: $550 USD<br />&nbsp;</li>
            
            <li>Adoption fee for Cats:<br />
            US and Canada: $150 USD<br />&nbsp;</li>
            <li>Note* Adoption fees may change without prior notice.</li>
            </ul>
            <p>&nbsp;</p>

            <p>Please be thorough on your application and submit it for
            review.
            </p>
            <p>&nbsp;</p>
            <ul className="list-disc">
            <li>Once your application has been reviewed, we will 
            be in contact. Please allow us a few days of review 
            before expecting to hear from us. Be aware that 
            there may be additional contact required, such as a 
            home visit before the adoption is approved. 
            Please understand that we want to make sure this is 
            a perfect fit for you as well as our rescue.
            <br />&nbsp;</li>

            <li>We will guide you through the transport process if 
            necessary and provide you with all the necessary 
            veterinary records regarding vaccinations, etc.
            <br />&nbsp;</li>

            <li>
            You will also need to agree to the terms of our 
            ADOPTION CONTRACT. Important to note that if any of 
            the terms of the contract are not honored it will 
            be considered a breach of contract, invalidating it 
            and allowing for retrieval of the animal back to the 
            SPCA PV.
            <br />&nbsp;</li>
            </ul>

      </div>

      </div>
      </div>
  )
}


export async function getServerSideProps() {
  //const notes = await prisma.note.findMany();
  //const res = await fetch(`https://shelter.spcapv.net/adopt/animals`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/dogs`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/cats`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/cats`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props: { data },
  };
}
