import Link from "next/link";
import Head from "next/head";
import Image from 'next/image'
//import prisma from "../../lib/prisma.ts";




export default function ShelterApi({ data }) {
  return (

    <div>
      <Head>
        <title>Cats - Available</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="flex-auto w-2/3 p-10">
          
      <h1 className="text-2xl font-black">Cats Available For Adoption</h1>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <ul>
          {data.map((item) => (
            <li key={item.id}>
         <div className="p-5">   
        <div className="card card-side w-96 bg-base-100 shadow-2xl">
  <figure><img src={item.photoMedium} alt={item.name} /></figure>
  <div className="card-body">
    <h2 className="card-title">
    {item.name}
      <div className="badge badge-warning">Available!</div>
    </h2>  
    <p className="text-sm">Gender: {item.gender}<br />
    Weight: {item.weight}<br />
    Age:&nbsp; 
    {item.myage == 0 && (
      <span>&lt; 1 Year</span>
     )}
     {item.myage > 0 && (
      <span>{item.myage}</span>
     )}

     
      </p>
              
    <div className="card-actions justify-end">
    <Link className="badge badge-outline" href={`/shelterapi/animal_details/${item.id}`}>Details</Link>  
    
      
    </div>
  </div>
</div>        
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>

</li>

          ))}
        </ul>







      </div>

      <div className="flex-auto w-1/3 p-5">
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1>Right Side</h1>

      </div>

      </div>
      </div>
  )
}


export async function getServerSideProps() {
  //const notes = await prisma.note.findMany();
  //const res = await fetch(`https://shelter.spcapv.net/adopt/animals`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/dogs`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/cats`)
  //const res = await fetch(`http://127.0.0.1:8000/adopt/cats`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props: { data },
  };
}
