import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
import Image from 'next/image'
import prisma from "../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const photo = await prisma.photo.findUnique({ where: { id: parseInt(id) } });
  
  return {
    props: {
      photo: JSON.parse(JSON.stringify(photo)),
    },
  };
}

async function deletePhoto(id) {
  await fetch(`/api/photos/deletePhoto/${id}`, {
    method: "DELETE",
  });
  Router.push("/photos");
}

export default function Photo(props) {
  //const router = useRouter();
  const { photo } = props;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{photo.caption}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Caption: {photo.caption}</p>
        {photo.s3Url && (
            <Image
              src={photo.s3Url}
              alt="A picture"
              width={300}
              height={300}
            />
          )}
        <p>&nbsp;</p>
        <p>ID: {photo.id}</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href={`/photos/editPhoto/${photo.id}`}>Edit</Link> &nbsp; &nbsp;
          <button
            className="delete button"
            onClick={() => {
              const confirmBox = window.confirm(
                "Do you really want to delete this Photo?"
              );
              if (confirmBox === true) {
                deletePhoto(photo.id);
              }
            }}
          >
            Delete
          </button>  
          &nbsp; &nbsp; <Link href={`/photos`}>Cancel</Link>&nbsp;
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
