import Link from "next/link";
import Head from "next/head";
import Image from 'next/image'
import { useSession } from "next-auth/react";



export default function AdoptAppDetail({ data }) {
  const { data: session } = useSession();
  let myid;
  if (session) 
    myid = session.id; 
  else
    myid = 0;
  


  return (
    
    <>
      <Head>
      {data.adopter_id == myid && (
        <title>{data.name}</title>
      )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.adopter_id == myid && (
      <div className="flex gap-10 flex-wrap">

        <div className="w-96 p-5">
        <p>Submission Status: <b>{data.publishStatus}</b></p>
        <p>&nbsp;</p>
        <h1 className="text-3xl font-black">{data.name}</h1>
        <p>&nbsp;</p>
        <p>To Adopt</p>
        <h1 className="text-3xl font-black">{data.nameAnimal}</h1>
        <p>&nbsp;</p>
        <Link className="badge badge-outline" 
          href={`/shelterapi/editAdoptApp/${data.id}`}>Edit</Link>  
        <p>&nbsp;</p>
        
      </div>

      
      <div className="flex-auto ml-10 w-auto h-14 p-5">
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">
          Animal to Adopt {data.nameAnimal}</h1>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">Details:</h1>
          <p>&nbsp;</p>
          <ul>
          <li><small><b>Full Name:</b></small> {data.name}<br />
          &nbsp;
          </li>
          <li><small><b>Email:</b></small> {data.email}<br />
          &nbsp;
          </li>
          <li><small><b>Street Address:</b></small> {data.street}<br />
          &nbsp;
          </li>
          <li><small><b>City:</b></small> {data.city}<br />
          &nbsp;
          </li>
          <li><small><b>State / Province:</b></small> {data.province}<br />
          &nbsp;
          </li>
          <li><small><b>Postal Code:</b></small> {data.postal}<br />
          &nbsp;
          </li>
          <li><small><b>Home Phone:</b></small> {data.homephone}<br />
          &nbsp;
          </li>
          <li><small><b>Cell Phone:</b></small> {data.cellphone}<br />
          &nbsp;
          </li>
          <li><small><b>Employer:</b></small> {data.employer}<br />
          &nbsp;
          </li>
          <li><small><b>Work Phone:</b></small> {data.workphone}<br />
          &nbsp;
          </li>
          <li><small><b>Can we contact you at work?:</b></small> {data.cancontact}<br />
          &nbsp;
          </li>
          <li><small><b>What kind of animal are you looking for?:</b></small><br />
           {data.whatKindAnimal}<br />
          &nbsp;
          </li>
          <li><small><b>Notes (private):</b></small><br />
          {data.notes}<br />
          &nbsp;
          </li>
          <li><small><b>Adopter ID:</b></small> {data.adopter_id}<br />
          &nbsp;
          </li>
          <li><small><b>What reason could make you want to return 
           a dog to the shelter?:</b></small><br />
           {data.reasonReturn}<br />
          &nbsp;
          </li>
          <li><small><b>Have you had pets in the past?:</b></small><br />
          {data.petsPast}<br />
          &nbsp;
          </li>
          <li><small><b>What pets do you currently have?:</b></small><br />
          {data.petsNow}<br />
          &nbsp;
          </li>
          <li><small><b>Are your pets up-to-date on vaccinations?:</b></small><br />
          {data.petsVaxed}<br />
          &nbsp;
          </li>
          <li><small><b>Would your pets accept a new dog or cat?:</b></small><br />
          {data.petsAcceptNew}<br />
          &nbsp;
          </li>
          <li><small><b>Where will the pet you are applying to adopt be 
            kept during the day or when no one is at home? 
            Where will it sleep? Where will it be when you are 
            at home?</b></small><br />
          {data.whereDuringDay}<br />
          &nbsp;
          </li>
          <li><small><b>Have you ever housebroken a puppy or dog? How would 
            you approach housebreaking a dog? Please explain in 
            detail.  We do not know if they have been housebroken.</b></small>
          <br />
          {data.housebreaking}<br />
          &nbsp;
          </li>
          <li><small><b>What will you feed your pet?  If a commercial food 
            which brand?</b></small><br />
          {data.whatFood}<br />
          &nbsp;
          </li>
          <li><small><b>If it is a dog, what kind of exercise will the 
            dog receive and how frequent?</b></small><br />
          {data.whatExercise}<br />
          &nbsp;
          </li>
          <li><small><b>If you travel, what arrangements do you make 
            for the care of your pets?</b></small><br />
          {data.travelHotel}<br />
          &nbsp;
          </li>
          <li><small><b>Have you ever relinquished a pet to a shelter or 
            rescue, or rehomed it? * If yes, please explain the 
            circumstances.</b></small><br />
          {data.sentBack}<br />
          &nbsp;
          </li>
          <li><small><b>HOUSING INFORMATION: Do you own or rent?  Is it a 
            house or apartment or condo? If renting, how long
             have you lived at this address? *If renting, 
             please provide landlord contact information.</b></small><br />
          {data.housingStatus}<br />
          &nbsp;
          </li>
          <li><small><b>If you are getting a dog, do you have a securely 
            fenced yard? Small dog proof? Jumping dog proof?
              What type of fencing?</b></small><br />
          {data.secureYard}<br />
          &nbsp;
          </li>
          <li><small><b>Are you planning on moving within the 
          next months/years? </b></small><br />
          {data.movingSoon}<br />
          &nbsp;
          </li>
          <li><small><b>YOUR FAMILY:  How many adults are in your home? Children?
          Is everyone living in your home agreeable to having a dog/cat?
          How would you describe the activity level of your 
          household? i.e. quiet, structured, busy, hectic etc...</b></small><br />
          {data.yourFamily}<br />
          &nbsp;
          </li>
          <li><small><b>Will it be an inside or outside dog / cat?</b></small><br />
          {data.insideDog}<br />
          &nbsp;
          </li>
          <li><small><b>Does anyone in your home have allergies? 
            Please describe.</b></small><br />
          {data.anyAllergies}<br />
          &nbsp;
          </li>
          <li><small><b>What forms of discipline do you feel are 
            appropriate for training or modifying behaviour in a 
            dog?  Are you familiar with rewards-based training methods 
            that do not involve physical force or dominance? </b></small><br />
          {data.disciplineStyle}<br />
          &nbsp;
          </li>
          <li><small><b>How much do you think you have to budget for expenses for 
            the dog / cat on a yearly basis? Can you afford it?</b></small><br />
          {data.budget}<br />
          &nbsp;
          </li>
          <li><small><b>Comments or Questions? Please feel free to include any 
            information that you feel we should know about you, your 
            family, your experience with pets.</b></small><br />
          {data.commentsQuestions}<br />
          &nbsp;
          </li>
          <li><small><b>Please provide us with at least two references in 
            addition to your vet. Please provide full name, telephone 
            number(s) and relationship for all references.</b></small><br />
          {data.twoRefs}<br />
          &nbsp;
          </li>

          
          
          <li>
          <Link className="badge badge-outline" 
          href={`/shelterapi/editAdoptApp/${data.id}`}>Edit</Link>  
          </li>
          </ul>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
      </div>
          
      </div>
      )}
      </>
      
  )
}


export async function getServerSideProps(context) {
  const id = context.params.id;
  //const res = await fetch(`http://127.0.0.1:8000/adopt/detail_adopt_app/${id}`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/detail_adopt_app/${id}`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props:  { data } ,
  };
}
