import Link from "next/link";
import Head from "next/head";
import Image from 'next/image'
import { useSession } from "next-auth/react";



export default function AdoptAppDetail({ data }) {
  const { data: session } = useSession();
  let myid;
  if (session) 
    myid = session.id; 
  else
    myid = 0;
  


  return (
    
    <>
      <Head>
      {data.adopter_id == myid && (
        <title>{data.name}</title>
      )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.adopter_id == myid && (
      <div className="flex gap-10 flex-wrap">

        <div className="w-96 p-5">
        <p>&nbsp;</p>
        <h1 className="text-3xl font-black">{data.name}</h1>
        <p>&nbsp;</p>
        
      </div>

      
      <div className="flex-auto ml-10 w-auto h-14 p-5">
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">
          Animal to Adopt {data.nameAnimal}</h1>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">Details:</h1>
          <p>&nbsp;</p>
          <ul>
          <li>Full Name: {data.name}<br />
          &nbsp;
          </li>
          <li>Email: {data.email}<br />
          &nbsp;
          </li>
          <li>Street Address: {data.street}<br />
          &nbsp;
          </li>
          <li>City: {data.city}<br />
          &nbsp;
          </li>
          <li>State / Province: {data.province}<br />
          &nbsp;
          </li>
          <li>Postal Code: {data.postal}<br />
          &nbsp;
          </li>
          <li>Home Phone: {data.homephone}<br />
          &nbsp;
          </li>
          <li>Cell Phone: {data.cellphone}<br />
          &nbsp;
          </li>
          <li>Employer: {data.employer}<br />
          &nbsp;
          </li>
          <li>Work Phone: {data.workphone}<br />
          &nbsp;
          </li>
          <li>Can we contact you at work?: {data.cancontact}<br />
          &nbsp;
          </li>
          <li>What kind of animal are you looking for?:<br />
           {data.whatKindAnimal}<br />
          &nbsp;
          </li>
          <li>Notes:<br />
          {data.notes}<br />
          &nbsp;
          </li>
          <li>Adopter ID: {data.adopter_id}<br />
          &nbsp;
          </li>
          
          
          
          

          
          
          
          
          
          
          <li>
          <Link className="badge badge-outline" 
          href={`/shelterapi/editAdoptApp/${data.id}`}>Edit</Link>  
          </li>
          </ul>
      </div>
          
      </div>
      )}
      </>
      
  )
}


export async function getServerSideProps(context) {
  const id = context.params.id;
  //const res = await fetch(`http://127.0.0.1:8000/adopt/detail_adopt_app/${id}`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/detail_adopt_app/${id}`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props:  { data } ,
  };
}
