import Link from "next/link";
import Head from "next/head";
import Image from 'next/image'
//import prisma from "../../lib/prisma.ts";




export default function AnimalDetail({ data }) {
  return (

    <div>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-8">
    <div className="p-2 rounded-md">
        <p>&nbsp;</p>
        <h1 className="text-3xl font-black">{data.name}</h1>
        <p>&nbsp;</p>
        <img className="rounded-lg" src={data.photoLarge} alt={data.name} />

      </div>

      <div className="p-2 rounded-md">
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">Adopt {data.name}</h1>
          <Link href="/shelterapi/adoptAppCreate">
          <button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-primary">Adoption Application</button>
          </Link>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1 className="text-1xl font-black">Details:</h1>
          <p>&nbsp;</p>
          <ul>
          <li>Name: {data.name}<br />
          &nbsp;
          </li>
          <li>Species: {data.species}<br />
          &nbsp;
          </li>
          <li>Gender:  {data.gender}<br />
          &nbsp;
          </li>
          <li>Age: {data.myage}<br />
          &nbsp;
          </li>
          <li>Weight: {data.weight}<br />
          &nbsp;
          </li>
          <li>Breed: {data.breed}<br />
          &nbsp;
          </li>
          <li>Current Status: {data.current_status}<br />
          &nbsp;
          </li>
          <li>Rescue Info: {data.rescueInfo}<br />
          &nbsp;
          </li>
          </ul>


      </div>

      </div>
      </div>
  )
}


export async function getServerSideProps(context) {
  const id = context.params.id;
  //const res = await fetch(`http://127.0.0.1:8000/adopt/cat_detail/${id}`)
  const res = await fetch(`https://shelter.spcapv.net/adopt/cat_detail/${id}`)
  const data = await res.json()
    
  return {
    //props: { data: JSON.parse(JSON.stringify(res)) },
    props:  { data } ,
  };
}
