import Link from "next/link";
import Head from "next/head";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/dist/client/router";




function HomePage() {
  const { data: session } = useSession();
  const router = useRouter();

  console.log("session", session);



  return <div className="main">
  <Head>
        <title>BShelter!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
  <h1 className="text-4xl font-bold">Welcome to BShelter.js!</h1>
  <p>&nbsp;</p>
  {session ? (
          <button onClick={() => signOut()}>Log out</button>
        ) : (
          <button
            onClick={() => {
              router.push("/api/auth/signin");
            }}
          >
            Sign in
          </button>
        )}
  <p>&nbsp;</p>
  <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/notes/newNote">Add New Note</Link>
        </div>
  <p>&nbsp;</p>
  </div>
}

export default HomePage