import Link from "next/link";
import Head from "next/head";
import { signOut, useSession, signIn } from "next-auth/react";
import { useRouter } from "next/dist/client/router";
import Image from 'next/image'




function HomePage() {
  const { data: session } = useSession();
  const router = useRouter();

  console.log("session", session);



  return <div className="main">
  <Head>
        <title>Adoption Center SPCAPV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  <p>&nbsp;</p>  
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-8">
    <div className="p-2 rounded-md">
    {!session && (
    <div>
    <button onClick={() => signIn(undefined, { callbackUrl: '/' })} 
    className="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-primary"
    >
    Log In
    </button>  
    <br /><br />
    You must registered and logged in to apply for an adoption.  It is easy and 
    we do not share your information with anyone.
    <p>&nbsp;</p>
    
     </div>
    )}
    <h1 className="text-1xl font-black">Dogs Available</h1>
    <p>&nbsp;</p>
    <Link href="/shelterapi/thedogs">
    <figure>
    <Image
    src="/images/davinci.png"
    height="191"
    width="370"
    alt="some name"
    />
    </figure>
    </Link>
    <p>&nbsp;</p>

    <Link href="/shelterapi/thedogs">   
    <p><u><b>View All Available Dogs</b></u></p>
    </Link>
    <p>&nbsp;</p>
    Some dogs are only available for adoption in Puerto Vallarta.
    You will see a PVOnly tag on the dogs page.
    <p>&nbsp;</p>
    Adoption Application links are on the dog&apos;s detail page.  
    It is a big blue button.
    <p>&nbsp;</p>

    

    <h1 className="text-1xl font-black">Adoption Fees</h1>
            <p>&nbsp;</p>
            <ul className="list-disc">
            <li>Adoption Fees for Dogs:<br />
            Mexico: $3,000 pesos<br />
            US and Canada: $550 USD<br />&nbsp;</li>
            <li>Note* Adoption fees may change without prior notice.</li>
            </ul>
            <p>&nbsp;</p>


    </div>


    <div className="p-2 rounded-md">
    {!session && (
    <div>
    <button onClick={() => { router.push("/register");
            }} 
    className="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-secondary"
    >
    Register!
    </button>  
    <br /><br />
    
     </div>
    )}
    <h1 className="text-1xl font-black">Cats Available</h1>
    <p>&nbsp;</p>
    <Link href="/shelterapi/thecats">
    <figure>
    <Image
    src="/images/nima.png"
    height="191"
    width="370"
    alt="some name"
    />
    </figure>
    </Link>
    <p>&nbsp;</p>

    <Link href="/shelterapi/thecats">   
    <p><u><b>View All Available Cats</b></u></p>
    </Link>
    <p>&nbsp;</p>
    Some cats are only available for adoption in Puerto Vallarta.
    You will see a PVOnly tag on the detail page.
    <p>&nbsp;</p>
    Adoption Application links are on the cat&apos;s detail page.  
    It is a big blue button.
    <p>&nbsp;</p>

    
    <h1 className="text-1xl font-black">Adoption Fees</h1>
            <p>&nbsp;</p>
            <ul className="list-disc">
            
            <li>Adoption fee for Cats:<br />
            US and Canada: $150 USD<br />&nbsp;</li>
            <li>Note* Adoption fees may change without prior notice.</li>
            </ul>
            <p>&nbsp;</p>

    
    
    
    </div>
    <div className="p-2"> 
    <figure>
    <Image
    src="/images/spca-pv1.gif"
    height="200"
    width="200"
    alt="some name"
    />
    </figure>
    <p>&nbsp;</p>

    <h1 className="text-1xl font-black">Adoption Center - SPCAPV</h1>

    <p>&nbsp;</p>

    {session ? (
            <Link href="/shelterapi/adoptAppCreate">
          <button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg btn-primary">Adoption Application</button>
          <br /><br />
          </Link>
          

          
        ) : (
          <p>You must be registered and logged in to access the Adoption
          Application.  Links are at the top of the page.<br /><br />
          Feel free to browse the available dogs and cats.  We never use your 
          registration information for anything other than the adoption process.
          </p>
          
        )}

  

  <p>&nbsp;</p>
  {session && (
  <div className="page-nav">
  <Link href={`/shelterapi/myapps/?key=${session.id}`}>My Applications</Link>
  
  </div>
  )}
  <p>&nbsp;</p>
  {session && (
    <div className="page-nav">
    <Link href="/shelterapi/adoptAppCreate">New Adoption Application</Link>
  </div>
  )}

  <p>&nbsp;</p>
  

  <p>&nbsp;</p>
  <p>&nbsp;</p>
  

    </div>
    </div>
  
  <p>&nbsp;</p>
 
  <p>End Main</p>
  </div>
}

export default HomePage