import { useState, useRef } from "react";
import Head from "next/head";
import Router from "next/router";
import prisma from "../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const photo = await prisma.photo.findUnique({ where: { id: parseInt(id) } });
  
  return {
    props: {
      photo: JSON.parse(JSON.stringify(photo)),
    },
  };
}

export default function EditPhoto({ photo }) {
  const formRef = useRef();
  const [disable, setDisable] = useState(false);
  async function editPhoto() {
    setDisable(true);
    const { editPhotoCaption, editPhotoS3Url } =
      formRef.current;
    const caption = editPhotoCaption.value;
    const s3Url = editPhotoS3Url.value;
    const id = parseInt(photo.id);

    //
    let formData = {
      caption,
      s3Url,
      
    };

    await fetch(`/api/photos/updatephoto/${id}`, {
      method: "PUT",
      body: JSON.stringify(formData),
    });
    setDisable(false);
    Router.push("/photos");
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Edit: {photo?.caption} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <div>
            <p>&nbsp;</p>
            <div className="page-nav">
              <h3>Edit Photo Details</h3>
            </div>
          </div>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <div className="label">
              <label>Caption</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={photo?.caption}
                name="editPhotoCaption"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>S3URL</label>
              <br />
            </div>
            <div>
              <input
                defaultValue={photo?.s3Url}
                name="editPhotoS3Url"
                type="text"
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              />
              <p>&nbsp;</p>
            </div>
          
            
          </form>
        </div>
        <div>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            disabled={disable}
            onClick={() => editPhoto()}
          >
            Save Changes
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
