import { useState, useRef } from "react";
import Router from "next/router";
import { useSession } from "next-auth/react";
import Head from "next/head";



export default function EditApp({ data }) {
  const { data: session } = useSession();
  let myid;
  
  if (session) 
    myid = session.id; 
  else
    myid = 0;

  const formRef = useRef();
  const [disable, setDisable] = useState(false);
  async function saveApp() {
    setDisable(true);
    const { editAppName, editAppEmail, editAppStreet, editAppProvince,  
        editAppNameAnimal, editAppCity, editAppPostal, editAppHomephone, 
      editAppCellphone, editAppEmployer, editAppWorkphone, editAppCancontact, 
      editAppwhatKindAnimal, editAppNotes, editAppReasonReturn,
    editAppPetsPast, editAppPetsNow, editAppPetsVaxed, editAppPetsAcceptNew,
    editAppWhereDuringDay, editAppHousebreaking, editAppWhatFood, 
    editAppWhatExercise, editAppTravelHotel, editAppSentBack, editAppHousingStatus,
    editAppSecureYard, editAppMovingSoon, editAppYourFamily, editAppInsideDog, 
    editAppAnyAllergies, editAppDisciplineStyle, editAppBudget, 
    editAppCommentsQuestions, editAppTwoRefs, editAppPublishStatus } =
      formRef.current;
    
      

    const id = parseInt(data.id);
    const name = editAppName.value;
    const email = editAppEmail.value;
    const nameAnimal = editAppNameAnimal.value;
    const street = editAppStreet.value;
    const city = editAppCity.value;
    const province = editAppProvince.value;
    const postal = editAppPostal.value;
    const homephone = editAppHomephone.value;
    const cellphone = editAppCellphone.value;
    const employer = editAppEmployer.value;
    const workphone = editAppWorkphone.value;
    const cancontact = editAppCancontact.value;
    const whatKindAnimal = editAppwhatKindAnimal.value;
    const notes = editAppNotes.value;   
    const reasonReturn = editAppReasonReturn.value;
    const petsPast = editAppPetsPast.value;
    const petsNow = editAppPetsNow.value;
    const petsVaxed = editAppPetsVaxed.value;
    const petsAcceptNew = editAppPetsAcceptNew.value;
    const whereDuringDay = editAppWhereDuringDay.value;
    const housebreaking = editAppHousebreaking.value;
    const whatFood = editAppWhatFood.value;
    const whatExercise = editAppWhatExercise.value;
    const travelHotel = editAppTravelHotel.value;
    const sentBack = editAppSentBack.value;
    const housingStatus = editAppHousingStatus.value;
    const secureYard = editAppSecureYard.value;
    const movingSoon = editAppMovingSoon.value;
    const yourFamily = editAppYourFamily.value;
    const insideDog = editAppInsideDog.value;
    const anyAllergies = editAppAnyAllergies.value;
    const disciplineStyle = editAppDisciplineStyle.value;
    const budget = editAppBudget.value;
    const commentsQuestions = editAppCommentsQuestions.value;
    const twoRefs = editAppTwoRefs.value;
    const publishStatus = editAppPublishStatus.value;
        
    console.log("cancontact:", cancontact);  

    let formData = {
      
      name,
      email,
      nameAnimal,
      street,
      city,
      province,
      postal,
      homephone,
      cellphone,
      employer,
      workphone,
      cancontact,
      whatKindAnimal,
      notes,
      reasonReturn,
      petsPast,
      petsNow,
      petsVaxed,
      petsAcceptNew,
      whereDuringDay,
      housebreaking,
      whatFood,
      whatExercise,
      travelHotel,
      sentBack,
      housingStatus,
      secureYard,
      movingSoon,
      yourFamily,
      insideDog,
      anyAllergies,
      disciplineStyle,
      budget,
      commentsQuestions,
      twoRefs,
      publishStatus,

      
    };

    const response = await fetch(`https://shelter.spcapv.net/adopt/update_adopt_app/${id}/`, {
      method: "PUT",
      body: JSON.stringify(formData),
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
    });
    setDisable(false);
    return await response.json(), await Router.push(`/shelterapi/myapps/?key=${session.id}`);
    
  }

  return (
    <div>
      <Head>
      {data.adopter_id == myid && (
        <title>Edit: {data?.name} </title>
      )}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.adopter_id == myid && (
      <main>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4 lg:gap-8">
    <div className="p-2 rounded-md">
    {/* This is the left column */} 
  
          <div>
            <p>&nbsp;</p>
            <div className="page-nav">
              <h3>Edit Application</h3>
            </div>
          </div>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <div className="label">
              <label><b>Your Full Name</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.name}
                name="editAppName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label><b>Name of the Animal That You Want to Adopt</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.nameAnimal}
                name="editAppNameAnimal"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label><b>Email</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.email}
                name="editAppEmail"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div>
            <div className="label">
              <label><b>Street Address</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.street}
                name="editAppStreet"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            </div>

            <div className="label">
              <label><b>Colonia and City</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.city}
                name="editAppCity"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>State or Province</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.province}
                name="editAppProvince"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>Postal Code</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.postal}
                name="editAppPostal"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>Home Phone</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.homephone}
                name="editAppHomephone"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>Cell Phone</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.cellphone}
                name="editAppCellphone"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>Employer</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.employer}
                name="editAppEmployer"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            <div className="label">
              <label><b>Work Phone</b></label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={data?.workphone}
                name="editAppWorkphone"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
            
            <div className="label">
              <label><b>Can we contact you at work?</b></label>
              <br />
            </div>
            <div>
            <select id="cancontact" 
            name="editAppCancontact"
            defaultValue={data?.cancontact}
            >
            <option value="">Select Yes or No</option>
            <option value="YES">Yes</option>
            <option value="NO">No</option>
            </select>
            <p>&nbsp;</p>
            </div>
           

            <div className="label">
              <label><b>What kind of animal are you looking for?</b></label>
              <br />
            </div>
            <div>
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppwhatKindAnimal"
              cols="40"
              rows="5"
              defaultValue={data?.whatKindAnimal}
              />
          </div>

          <div className="label">
              <label><b>Notes</b></label>
              <br />
            </div>
            <div>
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppNotes"
              cols="40"
              rows="5"
              defaultValue={data?.notes}
              />
          </div>

          <p>&nbsp;</p>
          <p>
            <b>What reasons would cause you to return the pet to us?:</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppReasonReturn"
              id=""
              cols="40"
              rows="2"
              defaultValue={data?.reasonReturn}
              placeholder="reason here..."
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Have you had pets in the past? If so, please describe. 
            Why are they no longer with you?</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppPetsPast"
              id=""
              cols="40"
              rows="2"
              defaultValue={data?.petsPast}
              placeholder="Past pets here ..."
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Please list pets you currently have in your home. 
            Include the following information in your list. 
            Dogs, cats comments on personality of each animal.  
            Are your pets spayed/neutered? If no, please explain.</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppPetsNow"
              id=""
              cols="40"
              rows="2"
              placeholder="Current pets here ..."
              defaultValue={data?.petsNow}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Are your pets up-to-date on vaccinations?  *The 
            name and phone number of your veterinarian are 
            mandatory*</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppPetsVaxed"
              id=""
              cols="40"
              rows="4"
              placeholder="Vaccinations yes or no.  Vet Info ..."
              defaultValue={data?.petsVaxed}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Would your pets accept a new dog or cat? What exposure 
            have they had with other pets in and out of your 
            home? What is their behaviour like with other animals?</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppPetsAcceptNew"
              id=""
              cols="40"
              rows="4"
              placeholder="Will your pets accept a new family member ..."
              defaultValue={data?.petsAcceptNew}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Where will the pet you are applying to adopt be 
            kept during the day or when no one is at home? 
            Where will it sleep? Where will it be when you are 
            at home?</b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppWhereDuringDay"
              id=""
              cols="40"
              rows="4"
              placeholder="Where will your pet be when you are at 
              work, when no one is home, at night.  Where will it sleep?"
              defaultValue={data?.whereDuringDay}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Have you ever housebroken a puppy or dog? How would 
            you approach housebreaking a dog? Please explain in 
            detail.  We do not know if they have been housebroken.
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppHousebreaking"
              id=""
              cols="40"
              rows="4"
              placeholder="Housebreaking experience.."
              defaultValue={data?.housebreaking}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>What will you feed your pet?  If a commercial food 
            which brand?
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppWhatFood"
              id=""
              cols="40"
              rows="2"
              placeholder="Type of food here ..."
              defaultValue={data?.whatFood}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>If it is a dog, what kind of exercise will the 
            dog receive and how frequent??
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppWhatExercise"
              id=""
              cols="40"
              rows="2"
              placeholder="Exercise here ..."
              defaultValue={data?.whatExercise}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>If you travel, what arrangements do you make 
            for the care of your pets?
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppTravelHotel"
              id=""
              cols="40"
              rows="2"
              placeholder="Travel arrangements here ..."
              defaultValue={data?.travelHotel}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Have you ever relinquished a pet to a shelter or 
            rescue, or rehomed it? * If yes, please explain the 
            circumstances.
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppSentBack"
              id=""
              cols="40"
              rows="2"
              placeholder="Ever sent back to shelter ..."
              defaultValue={data?.sentBack}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>HOUSING INFORMATION: Do you own or rent?  Is it a 
            house or apartment or condo? If renting, how long
             have you lived at this address? *If renting, 
             please provide landlord contact information

          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppHousingStatus"
              id=""
              cols="40"
              rows="4"
              placeholder="House or apartment or condo ..."
              defaultValue={data?.housingStatus}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>If you are getting a dog, do you have a securely 
            fenced yard? Small dog proof? Jumping dog proof?
              What type of fencing? 
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppSecureYard"
              id=""
              cols="40"
              rows="2"
              placeholder="Secure yard here ..."
              defaultValue={data?.secureYard}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Are you planning on moving within the next months/years? 
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppMovingSoon"
              id=""
              cols="40"
              rows="2"
              placeholder="Moving soon?? ..."
              defaultValue={data?.movingSoon}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>YOUR FAMILY:  First name and age of each adult 
            in your home? First name and age of each child in the home?
          Is everyone living in your home agreeable to having a dog/cat?
          How would you describe the activity level of your 
          household? i.e. quiet, structured, busy, hectic etc... 
          
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppYourFamily"
              id=""
              cols="40"
              rows="4"
              placeholder="Who is in the house? ..."
              defaultValue={data?.yourFamily}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Will it be an inside or outside dog / cat?
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppInsideDog"
              id=""
              cols="40"
              rows="2"
              placeholder="Inside dog or outside only?  Same applies 
              to cats ..."
              defaultValue={data?.insideDog}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Does anyone in your home have allergies? 
            Please describe.
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppAnyAllergies"
              id=""
              cols="40"
              rows="2"
              placeholder="Anybody have allergies?"
              defaultValue={data?.anyAllergies}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>What forms of discipline do you feel are 
            appropriate for training or modifying behaviour in a 
            dog?  Are you familiar with rewards-based training methods 
            that do not involve physical force or dominance? 
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppDisciplineStyle"
              id=""
              cols="40"
              rows="4"
              placeholder="Discipline style here ..."
              defaultValue={data?.disciplineStyle}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>How much do you think you have to budget for expenses for 
            the dog / cat on a yearly basis? Can you afford it?
            
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppBudget"
              id=""
              cols="40"
              rows="2"
              placeholder="Annual costs.  Food, vet, etc..."
              defaultValue={data?.budget}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Comments or Questions? Please feel free to include any 
            information that you feel we should know about you, your 
            family, your experience with pets.
            
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppCommentsQuestions"
              id=""
              cols="40"
              rows="4"
              placeholder="Comments or Questions?"
              defaultValue={data?.commentsQuestions}
              
            />
          </p>
          <p>&nbsp;</p>
          <p>
            <b>Please provide us with at least two references in 
            addition to your vet. Please provide full name, telephone 
            number(s) and relationship for all references.            
          </b>
            <br />
            <textarea
              className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              name="editAppTwoRefs"
              id=""
              cols="40"
              rows="4"
              placeholder="Two references please."
              defaultValue={data?.twoRefs}
              
            />
          </p>

          <p>&nbsp;</p>
          <div className="label">
              <label><b>Application Submission Status:</b></label>
              <br />
            </div>
            <div>
            <select id="publishStatus" 
            name="editAppPublishStatus"
            defaultValue={data?.publishStatus}
            
            >
            <option value="">Select Here</option>
            <option value="Draft">Draft</option>
            <option value="Published">Published</option>
            </select>
            </div>
          
            <p>&nbsp;</p>
          
          
            
          </form>
        


        <div>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            disabled={disable}
            onClick={() => saveApp()}
          >
            Save
          </button>
        </div>
        </div>

        <div className="p-2">
          
          {/* This is the right column */} 

          <h1 className="text-1xl font-bold">Take your time filling out the App!</h1>
              <p>&nbsp;</p>
              <ul className="list-disc">
              <li>Save it any time and come back later<br />&nbsp;</li>
              <li>By default you are in draft mode<br />&nbsp;</li>
              <li>When you are done - changing the setting above the save 
              button to publish<br />&nbsp;</li>
              <li>When you set your app to publish that will trigger 
              us to review it.<br />&nbsp;</li>
              <li>Good luck and thank you for your willingness to adopt!<br />&nbsp;</li>

              </ul>

              <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          



        </div>
        </div>
      
      </main>
        

      )}
      <footer className="text-center font-bold text-xl">
        <b>SPCAPV 2023</b>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
    const id = context.params.id;
    const res = await fetch(`https://shelter.spcapv.net/adopt/detail_adopt_app/${id}`)
    //const res = await fetch(`https://shelter.spcapv.net/adopt/dog_detail/${id}`)
    const data = await res.json()
      
    return {
      //props: { data: JSON.parse(JSON.stringify(res)) },
      props:  { data } ,
    };
  }
  